### ISSUE TITLE
How to set tg batch_size

### ISSUE THREAD

**Issue by honlzl** [andreagemelli/doc2graph#15]
When I train FUNSD e2e, Error appears on the relu function line:
![image](https://github.com/andreagemelli/doc2graph/assets/53089253/12d5325c-e60b-4e30-b5e8-6a9b1fc826ef)

RuntimeError: CUDA out of memory. Tried to allocate 4.21 GiB (GPU 0; 11.74 GiB total capacity; 4.55 GiB already allocated; 3.44 GiB free; 4.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.

batch_size: 16
epochs: 10000
lr: 1e-3
weight_decay: 1e-4
val_size : 0.1
optimizer: Adam # or AdamW, SGD - NOT YET IMPLEMENTED
scheduler:
   ReduceLROnPlateau # CosineAnnealingLR, None- NOT YET IMPLEMENTED  
stopper_metric: acc # loss or acc
seed: 42
the batch_size is useless,
train_graphs = [data.graphs[i] for i in train_index]
tg = dgl.batch(train_graphs)
tg = tg.int().to(device)

If I don't k-fold, train_graphs size is 149, so tg's batch_size is 149. Then  CUDA out of memory has occurred. I have tested both fully and knn, all error. How do I set tg batch_size to aviod RuntimeError.  train.yaml above seems to be useless.

My GPU is 12G 3060, Thank you!

**Comment by andreagemelli** [comment]
HI @HonLZL ,
for example in `src/training/funsd.py` in lines 48-49 I am batching together several graphs! 
You may try to replace those lines with a for cycle and passing each document page to the network instead of batching multiple together, e.g. commenting out those lines and passing each graph in `train_graphs` in line 78 instead of `tg`.
This should meet the memory constraints.
Let me know if you need more help.
A.

**Comment by honlzl** [comment]
> HI @HonLZL , for example in `src/training/funsd.py` in lines 48-49 I am batching together several graphs! You may try to replace those lines with a for cycle and passing each document page to the network instead of batching multiple together, e.g. commenting out those lines and passing each graph in `train_graphs` in line 78 instead of `tg`. This should meet the memory constraints. Let me know if you need more help. A.

Thank you for responding so quickly!  I solved this error by your way. Thanks again.

**Comment by honlzl** [comment]
Also, I would like to ask if F1 in the paper is F1-MICRO or F1-MACRO. Thank you very much!
